import { useState } from "react";
import { Modal } from "./ui";
import { downloadExportBlob } from "../lib/exportShare";

type ShareModalProps = {
  open: boolean;
  onClose: () => void;
  options: {
    blob: Blob;
    filename: string;
    title: string;
    text?: string;
    shareUrl: string;
  } | null;
};

export default function ShareModal({ open, onClose, options }: ShareModalProps) {
  const [copied, setCopied] = useState(false);

  if (!options) return null;
  const { blob, filename, title, text, shareUrl } = options;

  const handleCopy = async () => {
    try {
      await navigator.clipboard.writeText(shareUrl);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    } catch (err) {
      console.error("Clipboard copy failed:", err);
    }
  };

  const handleDownload = () => {
    downloadExportBlob(blob, filename);
  };

  const handleSystemShare = async () => {
    if (navigator.share) {
      try {
        await navigator.share({
          title,
          text: text || title,
          url: shareUrl,
        });
      } catch (err) {
        console.error("System share failed:", err);
      }
    }
  };

  const subject = encodeURIComponent(title);
  const emailBody = encodeURIComponent(
    `Here is the exported ${filename} from VERARA.\n\nView or download it online:\n${shareUrl}\n\nGenerated by VERARA Dashboard.`,
  );
  const whatsappText = encodeURIComponent(
    `*${title}* exported from VERARA.\n\nView online:\n${shareUrl}`,
  );
  const teamsText = encodeURIComponent(
    `Here is the VERARA report: ${shareUrl}`,
  );

  // App Sharing URLs
  const shareUrls = {
    email: `mailto:?subject=${subject}&body=${emailBody}`,
    gmail: `https://mail.google.com/mail/?view=cm&fs=1&su=${subject}&body=${emailBody}`,
    whatsapp: `https://api.whatsapp.com/send?text=${whatsappText}`,
    teams: `https://teams.microsoft.com/share?href=${encodeURIComponent(shareUrl)}&msgText=${teamsText}`,
    telegram: `https://t.me/share/url?url=${encodeURIComponent(shareUrl)}&text=${subject}`,
  };

  return (
    <Modal
      open={open}
      onClose={onClose}
      title="Share Exported Report"
      description="Select an application to share the generated report or copy the direct link."
      className="ui-modal-compact share-modal"
    >
      <div className="share-modal-container">
        {/* Link Copy Block */}
        <div className="share-link-group">
          <label className="share-label" htmlFor="share-link-input">Direct Share Link</label>
          <div className="share-link-input-wrapper">
            <input
              id="share-link-input"
              type="text"
              readOnly
              value={shareUrl}
              className="share-link-input"
              onClick={(e) => (e.target as HTMLInputElement).select()}
            />
            <button
              type="button"
              onClick={handleCopy}
              className={`share-copy-btn ${copied ? "copied" : ""}`}
            >
              {copied ? (
                <>
                  <svg viewBox="0 0 24 24" width="16" height="16" fill="none" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true">
                    <polyline points="20 6 9 17 4 12" />
                  </svg>
                  <span>Copied!</span>
                </>
              ) : (
                <>
                  <svg viewBox="0 0 24 24" width="16" height="16" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true">
                    <rect x="9" y="9" width="13" height="13" rx="2" ry="2" />
                    <path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1" />
                  </svg>
                  <span>Copy</span>
                </>
              )}
            </button>
          </div>
        </div>

        {/* Share Destination Tiles Grid */}
        <div className="share-grid">
          {/* Email */}
          <a href={shareUrls.email} className="share-tile share-tile-email">
            <div className="share-tile-icon">
              <svg viewBox="0 0 24 24" width="24" height="24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true">
                <path d="M4 4h16c1.1 0 2 .9 2 2v12c0 1.1-.9 2-2 2H4c-1.1 0-2-.9-2-2V6c0-1.1.9-2 2-2z" />
                <polyline points="22,6 12,13 2,6" />
              </svg>
            </div>
            <span className="share-tile-name">Email / Outlook</span>
          </a>

          {/* Gmail */}
          <a href={shareUrls.gmail} target="_blank" rel="noopener noreferrer" className="share-tile share-tile-gmail">
            <div className="share-tile-icon">
              <svg viewBox="0 0 24 24" width="24" height="24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true">
                <path d="M22 18V6a2 2 0 0 0-2-2H4a2 2 0 0 0-2 2v12c0 1.1.9 2 2 2h16a2 2 0 0 0 2-2z" />
                <path d="M22 6l-10 7L2 6" />
                <path d="M2 18l5.5-5.5M22 18l-5.5-5.5" />
              </svg>
            </div>
            <span className="share-tile-name">Gmail</span>
          </a>

          {/* WhatsApp */}
          <a href={shareUrls.whatsapp} target="_blank" rel="noopener noreferrer" className="share-tile share-tile-whatsapp">
            <div className="share-tile-icon">
              <svg viewBox="0 0 24 24" width="24" height="24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true">
                <path d="M21 11.5a8.38 8.38 0 0 1-.9 3.8 8.5 8.5 0 0 1-7.6 4.7 8.38 8.38 0 0 1-3.8-.9L3 21l1.9-5.7a8.38 8.38 0 0 1-.9-3.8 8.5 8.5 0 0 1 4.7-7.6 8.38 8.38 0 0 1 3.8-.9h.5a8.48 8.48 0 0 1 8 8v.5z" />
              </svg>
            </div>
            <span className="share-tile-name">WhatsApp</span>
          </a>

          {/* Teams */}
          <a href={shareUrls.teams} target="_blank" rel="noopener noreferrer" className="share-tile share-tile-teams">
            <div className="share-tile-icon">
              <svg viewBox="0 0 24 24" width="24" height="24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true">
                <rect x="3" y="3" width="18" height="18" rx="2" ry="2" />
                <path d="M9 12h6M12 9v6" />
              </svg>
            </div>
            <span className="share-tile-name">Teams</span>
          </a>

          {/* Telegram */}
          <a href={shareUrls.telegram} target="_blank" rel="noopener noreferrer" className="share-tile share-tile-telegram">
            <div className="share-tile-icon">
              <svg viewBox="0 0 24 24" width="24" height="24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true">
                <line x1="22" y1="2" x2="11" y2="13" />
                <polygon points="22 2 15 22 11 13 2 9 22 2" />
              </svg>
            </div>
            <span className="share-tile-name">Telegram</span>
          </a>

          {/* System Share */}
          {typeof navigator !== "undefined" && typeof navigator.share === "function" ? (
            <button type="button" onClick={handleSystemShare} className="share-tile share-tile-system">
              <div className="share-tile-icon">
                <svg viewBox="0 0 24 24" width="24" height="24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true">
                  <circle cx="18" cy="5" r="3" />
                  <circle cx="6" cy="12" r="3" />
                  <circle cx="18" cy="19" r="3" />
                  <line x1="8.59" y1="13.51" x2="15.42" y2="17.49" />
                  <line x1="15.41" y1="6.51" x2="8.59" y2="10.49" />
                </svg>
              </div>
              <span className="share-tile-name">System Share</span>
            </button>
          ) : null}

          {/* Direct Download Fallback */}
          <button type="button" onClick={handleDownload} className="share-tile share-tile-download">
            <div className="share-tile-icon">
              <svg viewBox="0 0 24 24" width="24" height="24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true">
                <path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4" />
                <polyline points="7 10 12 15 17 10" />
                <line x1="12" y1="15" x2="12" y2="3" />
              </svg>
            </div>
            <span className="share-tile-name">Download File</span>
          </button>
        </div>
      </div>
    </Modal>
  );
}
