"""Shared, A4 print primitives for the Verara/HospAI report family."""

from __future__ import annotations

from typing import Iterable, Sequence

from fpdf import FPDF


REPORT_LEFT_MARGIN = 20
REPORT_RIGHT_MARGIN = 20
REPORT_BOTTOM_MARGIN = 20


def format_report_amount(value) -> str:
    """Use the requested ASCII `Rs.` format in every report, including zero."""
    try:
        amount = float(value or 0)
    except (TypeError, ValueError):
        amount = 0
    return f"Rs. {amount:,.0f}"


class VeraraReportPDF(FPDF):
    """Base PDF with the shared running header and branded footer."""

    def __init__(self, font_name="Helvetica", generated_at=None, operator_name="Operator Name"):
        super().__init__(orientation="P", unit="mm", format="A4")
        self.font_name = font_name
        self.generated_at = generated_at
        self.operator_name = operator_name or "Operator Name"
        self.set_left_margin(REPORT_LEFT_MARGIN)
        self.set_right_margin(REPORT_RIGHT_MARGIN)
        self.set_top_margin(15)
        self.set_auto_page_break(auto=True, margin=REPORT_BOTTOM_MARGIN + 16)

    def header(self):
        if self.page_no() <= 1:
            return
        self.set_y(10)
        self.set_font(self.font_name, "", 7)
        self.set_text_color(80, 80, 80)
        self.cell(85, 4, "VERARA | Poly Clinic | Pharmacy | Diagnostic")
        self.cell(85, 4, f"Page {self.page_no()}/{{nb}}", align="R")
        self.set_text_color(0, 0, 0)

    def footer(self):
        # Kept compact on follow-on pages so report content never collides with it.
        if self.page_no() > 1:
            self.set_y(-14)
            self.set_draw_color(0, 0, 0)
            self.set_line_width(0.35)
            self.line(REPORT_LEFT_MARGIN, self.get_y(), 210 - REPORT_RIGHT_MARGIN, self.get_y())
            self.set_y(-10)
            self.set_font(self.font_name, "I", 7)
            self.cell(85, 4, "Thank you for choosing Verara Poly Clinic.")
            self.cell(85, 4, f"Page {self.page_no()}/{{nb}}", align="R")


def draw_report_header(pdf: VeraraReportPDF, logo_path: str | None):
    """Draw the common clinic header and its full-width black divider."""
    top = 16
    if logo_path:
        try:
            pdf.image(logo_path, x=REPORT_LEFT_MARGIN, y=top, w=76)
        except Exception:
            pass
    else:
        pdf.set_xy(REPORT_LEFT_MARGIN, top + 3)
        pdf.set_font(pdf.font_name, "B", 29)
        pdf.cell(76, 11, "VERARA")
        pdf.set_x(REPORT_LEFT_MARGIN)
        pdf.set_font(pdf.font_name, "", 10)
        pdf.cell(76, 5, "Poly Clinic | Pharmacy | Diagnostic")

    address = [
        "I-2-288/22/9,",
        "Ramakrishna Math Marg,",
        "Poolbagh, Aravindra Nagar,",
        "Domalguda, Himayatnagar,",
        "Hyderabad, Telangana 500029",
        "",
        "9949237676, 7032774699",
    ]
    pdf.set_xy(122, top)
    pdf.set_font(pdf.font_name, "", 9)
    for line in address:
        pdf.cell(68, 4.6, line, ln=True, align="R")
        pdf.set_x(122)

    divider_y = 53
    pdf.set_draw_color(0, 0, 0)
    pdf.set_line_width(0.7)  # approximately a 2px printed divider
    pdf.line(REPORT_LEFT_MARGIN, divider_y, 210 - REPORT_RIGHT_MARGIN, divider_y)
    pdf.set_line_width(0.2)
    pdf.set_y(divider_y + 5)


def draw_report_title_and_metadata(pdf: VeraraReportPDF, title: str, subtitle: str, generated_by: str = "HospAI System"):
    """Draw the left title/right metadata block used by all report types."""
    y = pdf.get_y()
    pdf.set_xy(REPORT_LEFT_MARGIN, y)
    pdf.set_font(pdf.font_name, "B", 16.5)
    pdf.cell(95, 7, title)
    pdf.set_x(REPORT_LEFT_MARGIN)
    pdf.set_font(pdf.font_name, "", 10.5)
    pdf.cell(95, 5.5, subtitle)

    timestamp = pdf.generated_at
    date_text = timestamp.strftime("%d/%m/%Y") if timestamp else "-"
    time_text = timestamp.strftime("%I:%M:%S %p") if timestamp else "-"
    meta_x, label_w, colon_w, value_w = 132, 29, 5, 24
    pdf.set_xy(meta_x, y + 0.5)
    pdf.set_font(pdf.font_name, "", 8.7)
    for label, value in (("Print Date", date_text), ("Generated By", generated_by), ("Generated Time", time_text)):
        pdf.cell(label_w, 5, label, align="L")
        pdf.cell(colon_w, 5, ":", align="C")
        pdf.cell(value_w, 5, value, ln=True, align="R")
        pdf.set_x(meta_x)
    pdf.set_y(y + 19)


def draw_section_heading(pdf: VeraraReportPDF, title: str):
    pdf.ln(2)
    pdf.set_font(pdf.font_name, "B", 13)
    pdf.cell(170, 6.5, title, ln=True)
    pdf.ln(0.5)


def _page_space(pdf: VeraraReportPDF, required_height: float):
    if pdf.get_y() + required_height > 267:
        pdf.add_page()
        pdf.set_y(18)


def draw_report_table(
    pdf: VeraraReportPDF,
    headers: Sequence[str],
    rows: Iterable[Sequence[object]],
    widths: Sequence[float],
    bold_last_row: bool = False,
):
    """Reusable bordered, gray-head table with predictable row heights."""
    rows = list(rows)
    # Compact but legible: this keeps the complete executive dashboard on one
    # A4 page without reducing the requested table padding below 8px-equivalent.
    row_height = 5.4
    _page_space(pdf, row_height * 2)
    pdf.set_fill_color(229, 229, 229)
    pdf.set_draw_color(0, 0, 0)
    pdf.set_line_width(0.2)
    pdf.set_font(pdf.font_name, "B", 7.8)
    for header, width in zip(headers, widths):
        pdf.cell(width, row_height, str(header), border=1, fill=True)
    pdf.ln(row_height)

    for index, row in enumerate(rows):
        _page_space(pdf, row_height)
        is_bold = bold_last_row and index == len(rows) - 1
        pdf.set_font(pdf.font_name, "B" if is_bold else "", 7.8)
        if index % 2:
            pdf.set_fill_color(250, 250, 250)
            fill = True
        else:
            fill = False
        for value, width in zip(row, widths):
            pdf.cell(width, row_height, str(value if value not in (None, "") else "0"), border=1, fill=fill)
        pdf.ln(row_height)
    pdf.ln(2.5)


def draw_light_logo_watermark(pdf: VeraraReportPDF, logo_path: str | None):
    """Place a 5–8% logo watermark behind the page content, when available."""
    if not logo_path:
        return
    try:
        # fpdf2 applies this graphic state to the image; use a deliberately light 6% opacity.
        with pdf.local_context(fill_opacity=0.06, stroke_opacity=0.06):
            pdf.image(logo_path, x=52, y=112, w=106)
    except Exception:
        # Watermarks must never prevent a report from being generated.
        pass


def draw_report_footer(pdf: VeraraReportPDF):
    """Draw the reference footer once on the final report page."""
    footer_y = 270
    pdf.set_y(footer_y - 16)
    pdf.set_font(pdf.font_name, "B", 8.5)
    pdf.cell(70, 5, pdf.operator_name)
    pdf.set_draw_color(0, 0, 0)
    pdf.set_line_width(0.3)
    pdf.line(REPORT_LEFT_MARGIN, footer_y - 8, 62, footer_y - 8)

    pdf.line(REPORT_LEFT_MARGIN, footer_y, 99, footer_y)
    pdf.line(111, footer_y, 210 - REPORT_RIGHT_MARGIN, footer_y)
    pdf.set_xy(99, footer_y - 4)
    pdf.set_font("Helvetica", "B", 18)
    pdf.cell(12, 7, "+", align="C")

    pdf.set_xy(REPORT_LEFT_MARGIN, footer_y + 3)
    pdf.set_font(pdf.font_name, "BI", 8.5)
    pdf.cell(88, 5, "Thank you for choosing Verara Poly Clinic.")
    pdf.set_x(111)
    pdf.cell(79, 5, "Valid for 7 days or 2 times.", align="R")
